### ISSUE TITLE
More than 100 Mapped Domains

### ISSUE THREAD

**Issue by davinian** [ircf/wp-cli-letsencrypt#1]
Hi, do you have any advise/suggestions for subdomain multisite with over 100 mapped domains?
Would wildcard for the subdomains/main vhost, then split the mapped domains in to multiple vhosts?

**Comment by mbautista** [comment]
Hello,
- AFAIK Let's Encrypt does not support wildcards
- One solution would be to refactor the code to split into batches of 100 domains and create a separate certificate (and then vhost) for each batch but that's beyond this CLI tool, and it seems it would be simpler and cleaner to just create a certificate/vhost for each website.

Our company also use this tool with more than 100 websites, for now we use this trick : 
`wp --allow-root letsencrypt --with-www=true --https-only=true`

The "https-only" option only include websites with URL "https://..." in the certificate, so you can have up to 50 HTTPS websites (50 with www, 50 without), and many more websites without HTTPS.

For now we don't have a solution to grow after 50 HTTPS websites in a wp network.

I think the next step for us is to completely drop this tool and create a separate vhost for each website in the network. For now we plan to create the vhost manually in our host panel even if it takes time.

An interesting solution would be to create a wp-cli "vhost-per-site" tool that would create automatically vhosts and certificates, but that would be too much work for us, so I think we'll stick to create each vhost manually for now.

Let me know if you find an elegant and automated solution for SAN above 100 websites.

EDIT : I think we should not modify this tool : the limitation is due to Let's Encrypt not the cli tool, so if one day LE allows more than 100 domains this will solve the problem by itself. As long as it's not the case, then it means that a SAN is not the correct approach for handling a huge amount of domains, and so we should use another tool than this one.

**Comment by davinian** [comment]
Thanks @mbautista for the reply.
We redirect all www to non-www and would just like to use https:// on all mapped domains.
I will reach out to Let's Encrypt community and see what options they suggest - maybe vhost for each domain or multiple SANs.
Kind regards 😄
